"""All business fields are first-class columns; JSON only for structured values.
Every table has UUID id, created_at, updated_at, created_by, deleted_at.
Audit rows keep the same columns but are append-only (including soft deletion).
"""
SCHEMA = {
"users": "full_name:text email:text phone:text role:text active:int two_fa_enabled:int last_login:text password_hash:text totp_secret:text last_totp_step:int failed_attempts:int locked_until:text",
"clients": "type:text full_name:text phone:text email:text messenger:text messenger_username:text source:text registration_address:text inn:text kpp:text ogrn:text bank_details:json comment:text manager_id:ref person_id:ref birth_date:text tags:json status:text contact_key:text",
"persons": "last_name_ru:text first_name_ru:text patronymic_ru:text gender:text birth_date:text citizenship:text birth_place:text phone:text email:text relationship:text clothing_size:text wishes:text needs_visa:int identity_key:text processing_blocked:int deletion_due:text legal_hold:int",
"client_person_relations": "client_id:ref person_id:ref relation_type:text is_primary:int status:text valid_from:text valid_to:text source:text verified_by:ref verified_at:text",
"external_subjects": "kind:text person_id:ref client_id:ref contact_key:text status:text",
"access_grants": "subject_type:text subject_id:text resource_type:text resource_id:text permissions:json valid_from:text expires_at:text granted_by:ref revoked_at:text reason:text",
"access_grant_events": "grant_id:ref event:text actor_id:ref reason:text occurred_at:text",
"data_migration_events": "migration:text entity_type:text entity_id:text outcome:text details:json occurred_at:text",
"identity_documents": "person_id:ref type:text series:text number:text issued_by:text division_code:text issue_date:text expiry_date:text last_name_latin:text first_name_latin:text issuing_country:text mrz_raw:text scan_file_id:ref verification_status:text confidence:json is_primary:int document_key:text manual_mrz_review:int",
"upload_batches": "operation_key:text requested_by:ref item_count:int status:text finished_at:text",
"upload_items": "batch_id:ref ordinal:int name:text file_id:ref content_hash:text mime:text status:text error_code:text ocr_run_id:ref duplicate_of:int",
"ocr_runs": "file_id:ref person_id:ref provider:text provider_version:text provider_request_id:text integration_state:text confidence_origin:text raw_confidence:json calibrated_confidence:json status:text warnings:json dedupe_hints:json idempotency_key:text",
"ocr_fields": "ocr_run_id:ref name:text value:text source:text raw_confidence:text confidence_origin:text calibrated_confidence:text critical:int confirmed:int confirmed_by:ref confirmed_at:text conflict:int possible_truncation:int",
"ocr_confirmations": "ocr_run_id:ref field_name:text value_hash:text confirmed_by:ref confirmed_at:text conflict_ack:int truncation_ack:int",
"integration_calls": "adapter:text operation:text idempotency_key:text attempt:int status:text duration_ms:int error_code:text",
"quarantine_files": "upload_item_id:ref person_id:ref name:text mime:text size:int storage_path:text content_key:text status:text scanner:text scanner_state:text scanned_at:text promoted_file_id:ref expires_at:text destroyed_at:text",
"file_scan_events": "quarantine_id:ref scanner:text scanner_state:text result:text duration_ms:int error_code:text checked_at:text",
"addresses": "person_id:ref type:text postal_code:text region:text city:text street:text house:text building:text apartment:text full_address:text",
"operators": "full_name:text short_name:text inn:text ogrn:text address:text registry_number:text guarantee_type:text guarantee_amount:int guarantor:text guarantee_number:text guarantee_from:text guarantee_to:text guarantee_address:text contacts:json portal_url:text default_commission_bps:int bank_details:json payment_hours:int agent_agreement:text",
"countries": "code:text name:text passport_months:int passport_days:int passport_rule_basis:text visa_required:int visa_lead_days:int memo:text rules_checked_at:text",
"hotels": "name:text country_id:ref city:text category:text address:text contacts:json",
"deals": "number:text client_id:ref manager_id:ref status:text country_id:ref city:text date_from:text date_to:text nights:int hotel:text room:text meal:text adults:int children:int infants:int flight_there:json flight_back:json tour_type:text booking_number:text operator_id:ref currency:text exchange_rate:text client_price:int operator_net:int commission:int paid_client:int paid_operator:int client_deadline:text operator_deadline:text cross_border:int comments:text program:text route:text guide:text services:text host_contacts:text recipients:json last_contact_at:text completed_at:text revision:int",
"deal_persons": "deal_id:ref person_id:ref role:text placement:text tariff:text parents_count:int notarized_consent_file_id:ref legal_representative_id:ref guardian_evidence_file_id:ref",
"contracts": "deal_id:ref number:text date:text type:text template_id:ref status:text pdf_file_id:ref file_hash:text signature_method:text signer_ip:text signer_phone:text sms_code_hash:text signed_at:text signed_file_id:ref signed_file_hash:text evidence:json document_id:ref agency_signed_at:text",
"documents": "deal_id:ref person_id:ref type:text source:text file_id:ref docx_file_id:ref version:int issued:int issued_at:text issue_channel:text template_id:ref template_version:int idempotency_key:text data_revision:int superseded:int",
"templates": "name:text type:text format:text body:text required_fields:json version:int active:int changed_by:ref",
"template_versions": "template_id:ref version:int body:text required_fields:json changed_by:ref",
"consents": "person_id:ref type:text received_at:text method:text expires_at:text revoked_at:text evidence_file_id:ref purposes:json recipients:json text_version:text representative_id:ref deal_id:ref ip:text user_agent:text",
"payments": "deal_id:ref direction:text amount:int currency:text date:text method:text receipt_number:text status:text external_id:text idempotency_key:text",
"tasks": "deal_id:ref type:text title:text due_at:text assignee_id:ref status:text automatic:int idempotency_key:text",
"notifications": "user_id:ref client_id:ref deal_id:ref channel:text template:text status:text date:text delivered_at:text payload:json destination:text idempotency_key:text attempts:int next_attempt:text lease_until:text provider_id:text last_error:text",
"notification_templates": "name:text channel:text body:text active:int",
"audit_log": "user_id:ref action:text entity:text entity_id:text details:json ip:text user_agent:text time:text previous_hash:text entry_hash:text",
"files": "name:text mime:text size:int storage_path:text encrypted:int retention_until:text uploaded_by:ref entity_type:text entity_id:text sha256:text",
"packages": "deal_id:ref type:text file_id:ref document_ids:json status:text issued_at:text opened_at:text idempotency_key:text missing:json",
"portal_links": "deal_id:ref client_id:ref person_id:ref token_hash:text expires_at:text consumed_at:text package_id:ref revoked_at:text",
"sessions": "user_id:ref link_id:ref token_hash:text csrf_hash:text last_seen:text expires_at:text revoked_at:text ip:text user_agent:text",
"otp_challenges": "link_id:ref contract_id:ref person_id:ref purpose:text phone:text code_hash:text expires_at:text attempts:int used_at:text binding_hash:text payload:json",
"messages": "deal_id:ref sender_id:ref sender_type:text body:text",
"job_runs": "name:text run_date:text finished_at:text",
"counters": "name:text value:int",
"rate_limits": "key:text window_start:int hits:int",
"settings": "name:text value:json",
"amendments": "deal_id:ref reason:text old_data:json new_data:json notified_operator:int",
}
JSON_FIELDS={t:{f.split(":")[0] for f in s.split() if f.endswith(":json")} for t,s in SCHEMA.items()}
INT_FIELDS={t:{f.split(":")[0] for f in s.split() if f.endswith(":int")} for t,s in SCHEMA.items()}
COLUMNS={t:[f.split(":")[0] for f in s.split()] for t,s in SCHEMA.items()}
PII = {
"users": {"phone","totp_secret"},
"clients": {"full_name","phone","email","registration_address","birth_date","comment","bank_details","messenger_username"},
"persons": {"last_name_ru","first_name_ru","patronymic_ru","birth_date","birth_place","phone","email","wishes"},
"identity_documents": {"series","number","issued_by","division_code","issue_date","expiry_date","last_name_latin","first_name_latin","mrz_raw","confidence"},
"upload_items": {"name"},
"ocr_fields": {"value"},
"quarantine_files": {"name"},
"access_grants": {"reason"},
"access_grant_events": {"reason"},
"addresses": set(COLUMNS["addresses"])-{"person_id","type"},
"contracts": {"signer_phone","signer_ip","evidence"},
"notifications": {"payload","destination"},
"otp_challenges": {"phone","payload"},
"messages": {"body"},
"amendments": {"old_data","new_data"},
}
FKS = {
"clients": {"manager_id":"users","person_id":"persons"},
"client_person_relations":{"client_id":"clients","person_id":"persons","verified_by":"users"},
"external_subjects":{"person_id":"persons","client_id":"clients"},
"access_grants":{"granted_by":"users"},
"access_grant_events":{"grant_id":"access_grants","actor_id":"users"},
"identity_documents":{"person_id":"persons","scan_file_id":"files"}, "addresses":{"person_id":"persons"},
"upload_batches":{"requested_by":"users"},
"upload_items":{"batch_id":"upload_batches","file_id":"files","ocr_run_id":"ocr_runs"},
"ocr_runs":{"file_id":"files","person_id":"persons"},
"ocr_fields":{"ocr_run_id":"ocr_runs","confirmed_by":"users"},
"ocr_confirmations":{"ocr_run_id":"ocr_runs","confirmed_by":"users"},
"quarantine_files":{"upload_item_id":"upload_items","person_id":"persons","promoted_file_id":"files"},
"file_scan_events":{"quarantine_id":"quarantine_files"},
"deals":{"client_id":"clients","manager_id":"users","country_id":"countries","operator_id":"operators"},
"deal_persons":{"deal_id":"deals","person_id":"persons","notarized_consent_file_id":"files","legal_representative_id":"persons","guardian_evidence_file_id":"files"},
"contracts":{"deal_id":"deals","template_id":"templates","pdf_file_id":"files","signed_file_id":"files","document_id":"documents"},
"documents":{"deal_id":"deals","person_id":"persons","file_id":"files","docx_file_id":"files","template_id":"templates"},
"template_versions":{"template_id":"templates"}, "consents":{"person_id":"persons","deal_id":"deals","evidence_file_id":"files","representative_id":"persons"},
"payments":{"deal_id":"deals"}, "tasks":{"deal_id":"deals","assignee_id":"users"},
"packages":{"deal_id":"deals","file_id":"files"}, "portal_links":{"deal_id":"deals","client_id":"clients","person_id":"persons","package_id":"packages"},
"sessions":{"user_id":"users","link_id":"portal_links"}, "otp_challenges":{"link_id":"portal_links","contract_id":"contracts","person_id":"persons"},
"messages":{"deal_id":"deals"}, "amendments":{"deal_id":"deals"}, "hotels":{"country_id":"countries"}
}
UNIQUE = [("users","email"),("countries","code"),("deals","number"),("identity_documents","document_key"),("upload_batches","operation_key"),("ocr_runs","idempotency_key"),("documents","idempotency_key"),("payments","idempotency_key"),("payments","external_id"),("tasks","idempotency_key"),("notifications","idempotency_key"),("portal_links","token_hash"),("sessions","token_hash"),("packages","idempotency_key"),("counters","name"),("settings","name"),("rate_limits","key")]
